# cloudbuild.yaml
steps:
# --- STEP 0: DEBUGGING ---
# This step prints variables and the file contents to the log.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "--- Verifying build configuration ---"
    echo "Project ID used by build: ${PROJECT_ID}"
    echo "Runtime SA for deploy step: function-runner@${PROJECT_ID}.iam.gserviceaccount.com"
    echo "--- Contents of cloudbuild.yaml at runtime ---"
    cat cloudbuild.yaml
    echo "-------------------------------------------"

# --- STEP 1: DEPLOYMENT ---
# This is your original deployment step.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'functions'
    - 'deploy'
    - 'hello-world-function'
    - '--gen2'
    - '--runtime=python311'
    - '--region=us-central1'
    - '--source=.'
    - '--entry-point=hello_http'
    - '--trigger-http'
    - '--allow-unauthenticated'
    - '--service-account=function-runner@${PROJECT_ID}.iam.gserviceaccount.com'

# Specify the service account for the build itself
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/your-build-service-account@${PROJECT_ID}.iam.gserviceaccount.com'

# Tell Cloud Build where to send the logs
options:
  logging: CLOUD_LOGGING_ONLY